# **Python - Numpy Basics**

In [10]:
import numpy as np

### **Numpy Array**

In [11]:
# 1D Array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
# 2D Array
b = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5]
])
print(b)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [13]:
# 3D Array
c = np.array([[
    [1,2,3,4,5],
    [1,2,3,4,5]],
    [[1,2,3,4,5],
    [1,2,3,4,5]],
    [[1,2,3,4,5],
    [1,2,3,4,5]
    ]])
print(c)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


In [14]:
import pandas as pd
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print("Shape:", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size: ", arr.itemsize)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension:  2
Size:  6
Data Type:  int64
Item Size:  8
