# **Python - Numpy Basics**

In [2]:
import numpy as np

### **Numpy Array**

In [3]:
# 1D Array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
# 2D Array
b = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5]
])
print(b)


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [5]:
# 3D Array
c = np.array([[
    [1,2,3,4,5],
    [1,2,3,4,5]],
    [[1,2,3,4,5],
    [1,2,3,4,5]],
    [[1,2,3,4,5],
    [1,2,3,4,5]
    ]])
print(c)

[[[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]]]


### **Array Attributes**

In [6]:
import pandas as pd
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print("Shape:", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size: ", arr.itemsize)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension:  2
Size:  6
Data Type:  int64
Item Size:  8


In [7]:
# Integer data type
arr1 = np.array([[1,2],[3,4]])
print(arr1.dtype)

# Float data type
arr2 = np.array([[1.0,2.0],[3.0,4.0]])
print(arr2.dtype)

# Forced data type
arr3 = np.array([1,2,3,4], dtype = np.int64)
print(arr3.dtype)

int64
float64
int64


### **Array Indexing**

In [8]:
# Accessing Numpy Array Elements
arr = np.arange(40,20,-2)
print("Elements: ", arr)

arr_ind = arr[np.array([3,1,2])]
print("Indices: ",arr_ind)

Elements:  [40 38 36 34 32 30 28 26 24 22]
Indices:  [34 38 36]


In [11]:
num = np.arange(15)
print("Array: ", num)

print("num[12]: ", num[12])

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
num[12]:  12


In [12]:
num[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
num[-5:13:1]

array([10, 11, 12])

In [18]:
num[3:10:2]

array([3, 5, 7, 9])

In [20]:
num1 = np.arange(10)
print(num1)

a = slice(2,7,2)
print(num1[a])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [21]:
# Integer Array Indexing / Advanced Indexing
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

print(a[[0, 1, 2], [1, 0, 0]])

[[1 2]
 [3 4]
 [5 6]]
[2 3 5]


In [22]:
# Boolean Indexing
a = np.array([37,43,62,94,29,27])
print(a[a<50])

[37 43 29 27]


### **Numpy - Bitwise Operator**

In [24]:
# Bitwise AND
print("Binary equivalents of 13 and 17: ")
a, b = 13, 17
print(bin(a), bin(b),'\n')
print("Bitwise AND of 13 and 17: ")
print(np.bitwise_and(13,17))

Binary equivalents of 13 and 17: 
0b1101 0b10001 

Bitwise AND of 13 and 17: 
1


In [25]:
# Bitwise OR
print("Binary equivalents of 13 and 17: ")
a, b = 13, 17
print(bin(a), bin(b),'\n')
print("Bitwise OR of 13 and 17: ")
print(np.bitwise_or(13,17))

Binary equivalents of 13 and 17: 
0b1101 0b10001 

Bitwise OR of 13 and 17: 
29


In [8]:
# Bitwise AND
print("Binary equivalents of 13 and 17: ")
a, b = 13, 17
print(bin(a), bin(b),'\n')
print("Bitwise AND of 13 and 17: ")
print(np.bitwise_and(13,17))